// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/entities/block_header.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockHeader struct {
	Id                   []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             []byte                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Height               uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9d8363da0276a74, []int{0}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *BlockHeader) GetParentId() []byte {
	if m != nil {
		return m.ParentId
	}
	return nil
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type EntireBlockHeader struct {
	Id                   []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             []byte                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Height               uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Witness              uint64                 `protobuf:"varint,5,opt,name=witness,proto3" json:"witness,omitempty"`
	VersionMe            uint64                 `protobuf:"varint,6,opt,name=version_me,json=versionMe,proto3" json:"version_me,omitempty"`
	VersionOp            uint64                 `protobuf:"varint,7,opt,name=version_op,json=versionOp,proto3" json:"version_op,omitempty"`
	VersionIdx           uint64                 `protobuf:"varint,8,opt,name=version_idx,json=versionIdx,proto3" json:"version_idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EntireBlockHeader) Reset()         { *m = EntireBlockHeader{} }
func (m *EntireBlockHeader) String() string { return proto.CompactTextString(m) }
func (*EntireBlockHeader) ProtoMessage()    {}
func (*EntireBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9d8363da0276a74, []int{1}
}

func (m *EntireBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntireBlockHeader.Unmarshal(m, b)
}
func (m *EntireBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntireBlockHeader.Marshal(b, m, deterministic)
}
func (m *EntireBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntireBlockHeader.Merge(m, src)
}
func (m *EntireBlockHeader) XXX_Size() int {
	return xxx_messageInfo_EntireBlockHeader.Size(m)
}
func (m *EntireBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_EntireBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_EntireBlockHeader proto.InternalMessageInfo

func (m *EntireBlockHeader) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *EntireBlockHeader) GetParentId() []byte {
	if m != nil {
		return m.ParentId
	}
	return nil
}

func (m *EntireBlockHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *EntireBlockHeader) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *EntireBlockHeader) GetWitness() uint64 {
	if m != nil {
		return m.Witness
	}
	return 0
}

func (m *EntireBlockHeader) GetVersionMe() uint64 {
	if m != nil {
		return m.VersionMe
	}
	return 0
}

func (m *EntireBlockHeader) GetVersionOp() uint64 {
	if m != nil {
		return m.VersionOp
	}
	return 0
}

func (m *EntireBlockHeader) GetVersionIdx() uint64 {
	if m != nil {
		return m.VersionIdx
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "flow.entities.BlockHeader")
	proto.RegisterType((*EntireBlockHeader)(nil), "flow.entities.EntireBlockHeader")
}

func init() { proto.RegisterFile("flow/entities/block_header.proto", fileDescriptor_b9d8363da0276a74) }

var fileDescriptor_b9d8363da0276a74 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0x87, 0x49, 0xde, 0xbe, 0xfd, 0x33, 0x55, 0xc1, 0x3d, 0xc8, 0x52, 0x95, 0x86, 0x9e, 0x7a,
	0xda, 0x15, 0xbd, 0x78, 0x2e, 0x08, 0xf6, 0x20, 0x4a, 0xf1, 0xe4, 0xa5, 0x34, 0xdd, 0x69, 0x32,
	0xd8, 0x64, 0x42, 0xb2, 0xb5, 0xfd, 0x0e, 0xfa, 0xa1, 0xa5, 0x9b, 0x6e, 0xb4, 0xdf, 0xc0, 0xcb,
	0xc2, 0xcc, 0xf3, 0xec, 0xec, 0x0f, 0x66, 0x21, 0x5a, 0xad, 0x79, 0xab, 0x31, 0xb7, 0x64, 0x09,
	0x2b, 0x1d, 0xaf, 0x79, 0xf9, 0x3e, 0x4f, 0x71, 0x61, 0xb0, 0x54, 0x45, 0xc9, 0x96, 0xc5, 0xe9,
	0xde, 0x50, 0xde, 0x18, 0x0c, 0x13, 0xe6, 0x64, 0x8d, 0xda, 0xc1, 0x78, 0xb3, 0xd2, 0x96, 0x32,
	0xac, 0xec, 0x22, 0x2b, 0x6a, 0x7f, 0xf4, 0x15, 0x40, 0x7f, 0xb2, 0x1f, 0xf3, 0xe8, 0xa6, 0x88,
	0x33, 0x08, 0xc9, 0xc8, 0x20, 0x0a, 0xc6, 0x27, 0xb3, 0x90, 0x8c, 0xb8, 0x84, 0x5e, 0xb1, 0x28,
	0x31, 0xb7, 0x73, 0x32, 0x32, 0x74, 0xed, 0x6e, 0xdd, 0x98, 0x1a, 0x71, 0x01, 0xed, 0x14, 0x29,
	0x49, 0xad, 0xfc, 0x17, 0x05, 0xe3, 0xd6, 0xec, 0x50, 0x89, 0x7b, 0xe8, 0x35, 0xef, 0xc8, 0x56,
	0x14, 0x8c, 0xfb, 0xb7, 0x03, 0x55, 0x27, 0x51, 0x3e, 0x89, 0x7a, 0xf5, 0xc6, 0xec, 0x47, 0x1e,
	0x7d, 0x86, 0x70, 0xfe, 0x90, 0x5b, 0x2a, 0xf1, 0xef, 0x84, 0x12, 0x12, 0x3a, 0x5b, 0xb2, 0x39,
	0x56, 0x95, 0xfc, 0xef, 0x46, 0xfa, 0x52, 0x5c, 0x03, 0x7c, 0x60, 0x59, 0x11, 0xe7, 0xf3, 0x0c,
	0x65, 0xdb, 0xc1, 0xde, 0xa1, 0xf3, 0x84, 0xbf, 0x31, 0x17, 0xb2, 0x73, 0x84, 0x9f, 0x0b, 0x31,
	0x84, 0xbe, 0xc7, 0x64, 0x76, 0xb2, 0xeb, 0xb8, 0xbf, 0x31, 0x35, 0xbb, 0xc9, 0x0b, 0x5c, 0x71,
	0x99, 0x28, 0xce, 0xdd, 0x52, 0x9b, 0x90, 0x7e, 0xbb, 0x6f, 0x37, 0x09, 0xd9, 0x74, 0x13, 0xab,
	0x25, 0x67, 0xba, 0x96, 0xb4, 0x3b, 0x9a, 0x6d, 0x27, 0xac, 0x8f, 0x7e, 0x4c, 0xdc, 0x76, 0xe8,
	0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x89, 0x44, 0xf6, 0xc9, 0x49, 0x02, 0x00, 0x00,
}
