// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/access/access.proto

package access

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	entities "github.com/onflow/flow/protobuf/go/flow/entities"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type GetLatestBlockHeaderRequest struct {
	IsSealed             bool     `protobuf:"varint,1,opt,name=is_sealed,json=isSealed,proto3" json:"is_sealed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestBlockHeaderRequest) Reset()         { *m = GetLatestBlockHeaderRequest{} }
func (m *GetLatestBlockHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestBlockHeaderRequest) ProtoMessage()    {}
func (*GetLatestBlockHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{2}
}

func (m *GetLatestBlockHeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestBlockHeaderRequest.Unmarshal(m, b)
}
func (m *GetLatestBlockHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestBlockHeaderRequest.Marshal(b, m, deterministic)
}
func (m *GetLatestBlockHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestBlockHeaderRequest.Merge(m, src)
}
func (m *GetLatestBlockHeaderRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestBlockHeaderRequest.Size(m)
}
func (m *GetLatestBlockHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestBlockHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestBlockHeaderRequest proto.InternalMessageInfo

func (m *GetLatestBlockHeaderRequest) GetIsSealed() bool {
	if m != nil {
		return m.IsSealed
	}
	return false
}

type GetBlockHeaderByIDRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHeaderByIDRequest) Reset()         { *m = GetBlockHeaderByIDRequest{} }
func (m *GetBlockHeaderByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockHeaderByIDRequest) ProtoMessage()    {}
func (*GetBlockHeaderByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{3}
}

func (m *GetBlockHeaderByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHeaderByIDRequest.Unmarshal(m, b)
}
func (m *GetBlockHeaderByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHeaderByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockHeaderByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeaderByIDRequest.Merge(m, src)
}
func (m *GetBlockHeaderByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockHeaderByIDRequest.Size(m)
}
func (m *GetBlockHeaderByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeaderByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeaderByIDRequest proto.InternalMessageInfo

func (m *GetBlockHeaderByIDRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetBlockHeaderByHeightRequest struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHeaderByHeightRequest) Reset()         { *m = GetBlockHeaderByHeightRequest{} }
func (m *GetBlockHeaderByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockHeaderByHeightRequest) ProtoMessage()    {}
func (*GetBlockHeaderByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{4}
}

func (m *GetBlockHeaderByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHeaderByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockHeaderByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHeaderByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockHeaderByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeaderByHeightRequest.Merge(m, src)
}
func (m *GetBlockHeaderByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockHeaderByHeightRequest.Size(m)
}
func (m *GetBlockHeaderByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeaderByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeaderByHeightRequest proto.InternalMessageInfo

func (m *GetBlockHeaderByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockHeaderResponse struct {
	Block                *entities.BlockHeader `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BlockHeaderResponse) Reset()         { *m = BlockHeaderResponse{} }
func (m *BlockHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderResponse) ProtoMessage()    {}
func (*BlockHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{5}
}

func (m *BlockHeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderResponse.Unmarshal(m, b)
}
func (m *BlockHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderResponse.Marshal(b, m, deterministic)
}
func (m *BlockHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderResponse.Merge(m, src)
}
func (m *BlockHeaderResponse) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderResponse.Size(m)
}
func (m *BlockHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderResponse proto.InternalMessageInfo

func (m *BlockHeaderResponse) GetBlock() *entities.BlockHeader {
	if m != nil {
		return m.Block
	}
	return nil
}

type EntireBlockHeaderResponse struct {
	Block                *entities.EntireBlockHeader `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *EntireBlockHeaderResponse) Reset()         { *m = EntireBlockHeaderResponse{} }
func (m *EntireBlockHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*EntireBlockHeaderResponse) ProtoMessage()    {}
func (*EntireBlockHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{6}
}

func (m *EntireBlockHeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntireBlockHeaderResponse.Unmarshal(m, b)
}
func (m *EntireBlockHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntireBlockHeaderResponse.Marshal(b, m, deterministic)
}
func (m *EntireBlockHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntireBlockHeaderResponse.Merge(m, src)
}
func (m *EntireBlockHeaderResponse) XXX_Size() int {
	return xxx_messageInfo_EntireBlockHeaderResponse.Size(m)
}
func (m *EntireBlockHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EntireBlockHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EntireBlockHeaderResponse proto.InternalMessageInfo

func (m *EntireBlockHeaderResponse) GetBlock() *entities.EntireBlockHeader {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetLatestBlockRequest struct {
	IsSealed             bool     `protobuf:"varint,1,opt,name=is_sealed,json=isSealed,proto3" json:"is_sealed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestBlockRequest) Reset()         { *m = GetLatestBlockRequest{} }
func (m *GetLatestBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestBlockRequest) ProtoMessage()    {}
func (*GetLatestBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{7}
}

func (m *GetLatestBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestBlockRequest.Unmarshal(m, b)
}
func (m *GetLatestBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestBlockRequest.Marshal(b, m, deterministic)
}
func (m *GetLatestBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestBlockRequest.Merge(m, src)
}
func (m *GetLatestBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestBlockRequest.Size(m)
}
func (m *GetLatestBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestBlockRequest proto.InternalMessageInfo

func (m *GetLatestBlockRequest) GetIsSealed() bool {
	if m != nil {
		return m.IsSealed
	}
	return false
}

type GetBlockByIDRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByIDRequest) Reset()         { *m = GetBlockByIDRequest{} }
func (m *GetBlockByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByIDRequest) ProtoMessage()    {}
func (*GetBlockByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{8}
}

func (m *GetBlockByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByIDRequest.Unmarshal(m, b)
}
func (m *GetBlockByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByIDRequest.Merge(m, src)
}
func (m *GetBlockByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByIDRequest.Size(m)
}
func (m *GetBlockByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByIDRequest proto.InternalMessageInfo

func (m *GetBlockByIDRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetBlockByHeightRequest struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHeightRequest) Reset()         { *m = GetBlockByHeightRequest{} }
func (m *GetBlockByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHeightRequest) ProtoMessage()    {}
func (*GetBlockByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{9}
}

func (m *GetBlockByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHeightRequest.Merge(m, src)
}
func (m *GetBlockByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHeightRequest.Size(m)
}
func (m *GetBlockByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHeightRequest proto.InternalMessageInfo

func (m *GetBlockByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockResponse struct {
	Block                *entities.Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{10}
}

func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetBlock() *entities.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetCollectionByIDRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCollectionByIDRequest) Reset()         { *m = GetCollectionByIDRequest{} }
func (m *GetCollectionByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetCollectionByIDRequest) ProtoMessage()    {}
func (*GetCollectionByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{11}
}

func (m *GetCollectionByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollectionByIDRequest.Unmarshal(m, b)
}
func (m *GetCollectionByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollectionByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetCollectionByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollectionByIDRequest.Merge(m, src)
}
func (m *GetCollectionByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetCollectionByIDRequest.Size(m)
}
func (m *GetCollectionByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollectionByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollectionByIDRequest proto.InternalMessageInfo

func (m *GetCollectionByIDRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type CollectionResponse struct {
	Collection           *entities.Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CollectionResponse) Reset()         { *m = CollectionResponse{} }
func (m *CollectionResponse) String() string { return proto.CompactTextString(m) }
func (*CollectionResponse) ProtoMessage()    {}
func (*CollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{12}
}

func (m *CollectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionResponse.Unmarshal(m, b)
}
func (m *CollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionResponse.Marshal(b, m, deterministic)
}
func (m *CollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionResponse.Merge(m, src)
}
func (m *CollectionResponse) XXX_Size() int {
	return xxx_messageInfo_CollectionResponse.Size(m)
}
func (m *CollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionResponse proto.InternalMessageInfo

func (m *CollectionResponse) GetCollection() *entities.Collection {
	if m != nil {
		return m.Collection
	}
	return nil
}

type SendTransactionRequest struct {
	Transaction          *entities.Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{13}
}

func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(m, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetTransaction() *entities.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type SendTransactionResponse struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionResponse) Reset()         { *m = SendTransactionResponse{} }
func (m *SendTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SendTransactionResponse) ProtoMessage()    {}
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{14}
}

func (m *SendTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionResponse.Unmarshal(m, b)
}
func (m *SendTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionResponse.Marshal(b, m, deterministic)
}
func (m *SendTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionResponse.Merge(m, src)
}
func (m *SendTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_SendTransactionResponse.Size(m)
}
func (m *SendTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionResponse proto.InternalMessageInfo

func (m *SendTransactionResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetTransactionRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionRequest) Reset()         { *m = GetTransactionRequest{} }
func (m *GetTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionRequest) ProtoMessage()    {}
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{15}
}

func (m *GetTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionRequest.Unmarshal(m, b)
}
func (m *GetTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionRequest.Merge(m, src)
}
func (m *GetTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionRequest.Size(m)
}
func (m *GetTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionRequest proto.InternalMessageInfo

func (m *GetTransactionRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type TransactionResponse struct {
	Transaction          *entities.Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{16}
}

func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetTransaction() *entities.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type TransactionResultResponse struct {
	Status               entities.TransactionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=flow.entities.TransactionStatus" json:"status,omitempty"`
	StatusCode           uint32                     `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrorMessage         string                     `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Events               []*entities.Event          `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	BlockId              []byte                     `protobuf:"bytes,5,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TransactionResultResponse) Reset()         { *m = TransactionResultResponse{} }
func (m *TransactionResultResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResultResponse) ProtoMessage()    {}
func (*TransactionResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{17}
}

func (m *TransactionResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResultResponse.Unmarshal(m, b)
}
func (m *TransactionResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResultResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResultResponse.Merge(m, src)
}
func (m *TransactionResultResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResultResponse.Size(m)
}
func (m *TransactionResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResultResponse proto.InternalMessageInfo

func (m *TransactionResultResponse) GetStatus() entities.TransactionStatus {
	if m != nil {
		return m.Status
	}
	return entities.TransactionStatus_UNKNOWN
}

func (m *TransactionResultResponse) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *TransactionResultResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *TransactionResultResponse) GetEvents() []*entities.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *TransactionResultResponse) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

type GetAccountRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{18}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type GetAccountResponse struct {
	Account              *entities.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{19}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccount() *entities.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type GetAccountAtLatestBlockRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountAtLatestBlockRequest) Reset()         { *m = GetAccountAtLatestBlockRequest{} }
func (m *GetAccountAtLatestBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountAtLatestBlockRequest) ProtoMessage()    {}
func (*GetAccountAtLatestBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{20}
}

func (m *GetAccountAtLatestBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountAtLatestBlockRequest.Unmarshal(m, b)
}
func (m *GetAccountAtLatestBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountAtLatestBlockRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountAtLatestBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountAtLatestBlockRequest.Merge(m, src)
}
func (m *GetAccountAtLatestBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountAtLatestBlockRequest.Size(m)
}
func (m *GetAccountAtLatestBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountAtLatestBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountAtLatestBlockRequest proto.InternalMessageInfo

func (m *GetAccountAtLatestBlockRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type AccountResponse struct {
	Account              *entities.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{21}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAccount() *entities.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type GetAccountAtBlockHeightRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BlockHeight          uint64   `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountAtBlockHeightRequest) Reset()         { *m = GetAccountAtBlockHeightRequest{} }
func (m *GetAccountAtBlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountAtBlockHeightRequest) ProtoMessage()    {}
func (*GetAccountAtBlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{22}
}

func (m *GetAccountAtBlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountAtBlockHeightRequest.Unmarshal(m, b)
}
func (m *GetAccountAtBlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountAtBlockHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountAtBlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountAtBlockHeightRequest.Merge(m, src)
}
func (m *GetAccountAtBlockHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountAtBlockHeightRequest.Size(m)
}
func (m *GetAccountAtBlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountAtBlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountAtBlockHeightRequest proto.InternalMessageInfo

func (m *GetAccountAtBlockHeightRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetAccountAtBlockHeightRequest) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type ExecuteScriptAtLatestBlockRequest struct {
	Script               []byte   `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	Arguments            [][]byte `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptAtLatestBlockRequest) Reset()         { *m = ExecuteScriptAtLatestBlockRequest{} }
func (m *ExecuteScriptAtLatestBlockRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptAtLatestBlockRequest) ProtoMessage()    {}
func (*ExecuteScriptAtLatestBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{23}
}

func (m *ExecuteScriptAtLatestBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.Unmarshal(m, b)
}
func (m *ExecuteScriptAtLatestBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptAtLatestBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.Merge(m, src)
}
func (m *ExecuteScriptAtLatestBlockRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.Size(m)
}
func (m *ExecuteScriptAtLatestBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptAtLatestBlockRequest proto.InternalMessageInfo

func (m *ExecuteScriptAtLatestBlockRequest) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *ExecuteScriptAtLatestBlockRequest) GetArguments() [][]byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type ExecuteScriptAtBlockIDRequest struct {
	BlockId              []byte   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Script               []byte   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Arguments            [][]byte `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptAtBlockIDRequest) Reset()         { *m = ExecuteScriptAtBlockIDRequest{} }
func (m *ExecuteScriptAtBlockIDRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptAtBlockIDRequest) ProtoMessage()    {}
func (*ExecuteScriptAtBlockIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{24}
}

func (m *ExecuteScriptAtBlockIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptAtBlockIDRequest.Unmarshal(m, b)
}
func (m *ExecuteScriptAtBlockIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptAtBlockIDRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptAtBlockIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptAtBlockIDRequest.Merge(m, src)
}
func (m *ExecuteScriptAtBlockIDRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptAtBlockIDRequest.Size(m)
}
func (m *ExecuteScriptAtBlockIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptAtBlockIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptAtBlockIDRequest proto.InternalMessageInfo

func (m *ExecuteScriptAtBlockIDRequest) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *ExecuteScriptAtBlockIDRequest) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *ExecuteScriptAtBlockIDRequest) GetArguments() [][]byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type ExecuteScriptAtBlockHeightRequest struct {
	BlockHeight          uint64   `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Script               []byte   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Arguments            [][]byte `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptAtBlockHeightRequest) Reset()         { *m = ExecuteScriptAtBlockHeightRequest{} }
func (m *ExecuteScriptAtBlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptAtBlockHeightRequest) ProtoMessage()    {}
func (*ExecuteScriptAtBlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{25}
}

func (m *ExecuteScriptAtBlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.Unmarshal(m, b)
}
func (m *ExecuteScriptAtBlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptAtBlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.Merge(m, src)
}
func (m *ExecuteScriptAtBlockHeightRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.Size(m)
}
func (m *ExecuteScriptAtBlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptAtBlockHeightRequest proto.InternalMessageInfo

func (m *ExecuteScriptAtBlockHeightRequest) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ExecuteScriptAtBlockHeightRequest) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *ExecuteScriptAtBlockHeightRequest) GetArguments() [][]byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type ExecuteScriptResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptResponse) Reset()         { *m = ExecuteScriptResponse{} }
func (m *ExecuteScriptResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptResponse) ProtoMessage()    {}
func (*ExecuteScriptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{26}
}

func (m *ExecuteScriptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptResponse.Unmarshal(m, b)
}
func (m *ExecuteScriptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptResponse.Merge(m, src)
}
func (m *ExecuteScriptResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptResponse.Size(m)
}
func (m *ExecuteScriptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptResponse proto.InternalMessageInfo

func (m *ExecuteScriptResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetEventsForHeightRangeRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	StartHeight          uint64   `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight            uint64   `protobuf:"varint,3,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsForHeightRangeRequest) Reset()         { *m = GetEventsForHeightRangeRequest{} }
func (m *GetEventsForHeightRangeRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsForHeightRangeRequest) ProtoMessage()    {}
func (*GetEventsForHeightRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{27}
}

func (m *GetEventsForHeightRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForHeightRangeRequest.Unmarshal(m, b)
}
func (m *GetEventsForHeightRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForHeightRangeRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsForHeightRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForHeightRangeRequest.Merge(m, src)
}
func (m *GetEventsForHeightRangeRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsForHeightRangeRequest.Size(m)
}
func (m *GetEventsForHeightRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForHeightRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForHeightRangeRequest proto.InternalMessageInfo

func (m *GetEventsForHeightRangeRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetEventsForHeightRangeRequest) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *GetEventsForHeightRangeRequest) GetEndHeight() uint64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

type GetEventsForBlockIDsRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	BlockIds             [][]byte `protobuf:"bytes,2,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsForBlockIDsRequest) Reset()         { *m = GetEventsForBlockIDsRequest{} }
func (m *GetEventsForBlockIDsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsForBlockIDsRequest) ProtoMessage()    {}
func (*GetEventsForBlockIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{28}
}

func (m *GetEventsForBlockIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsForBlockIDsRequest.Unmarshal(m, b)
}
func (m *GetEventsForBlockIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsForBlockIDsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsForBlockIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsForBlockIDsRequest.Merge(m, src)
}
func (m *GetEventsForBlockIDsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsForBlockIDsRequest.Size(m)
}
func (m *GetEventsForBlockIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsForBlockIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsForBlockIDsRequest proto.InternalMessageInfo

func (m *GetEventsForBlockIDsRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetEventsForBlockIDsRequest) GetBlockIds() [][]byte {
	if m != nil {
		return m.BlockIds
	}
	return nil
}

type EventsResponse struct {
	Results              []*EventsResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *EventsResponse) Reset()         { *m = EventsResponse{} }
func (m *EventsResponse) String() string { return proto.CompactTextString(m) }
func (*EventsResponse) ProtoMessage()    {}
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{29}
}

func (m *EventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsResponse.Unmarshal(m, b)
}
func (m *EventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsResponse.Marshal(b, m, deterministic)
}
func (m *EventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse.Merge(m, src)
}
func (m *EventsResponse) XXX_Size() int {
	return xxx_messageInfo_EventsResponse.Size(m)
}
func (m *EventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse proto.InternalMessageInfo

func (m *EventsResponse) GetResults() []*EventsResponse_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type EventsResponse_Result struct {
	BlockId              []byte                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	BlockHeight          uint64                 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Events               []*entities.Event      `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	BlockTimestamp       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EventsResponse_Result) Reset()         { *m = EventsResponse_Result{} }
func (m *EventsResponse_Result) String() string { return proto.CompactTextString(m) }
func (*EventsResponse_Result) ProtoMessage()    {}
func (*EventsResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{29, 0}
}

func (m *EventsResponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsResponse_Result.Unmarshal(m, b)
}
func (m *EventsResponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsResponse_Result.Marshal(b, m, deterministic)
}
func (m *EventsResponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse_Result.Merge(m, src)
}
func (m *EventsResponse_Result) XXX_Size() int {
	return xxx_messageInfo_EventsResponse_Result.Size(m)
}
func (m *EventsResponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse_Result proto.InternalMessageInfo

func (m *EventsResponse_Result) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *EventsResponse_Result) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *EventsResponse_Result) GetEvents() []*entities.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *EventsResponse_Result) GetBlockTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.BlockTimestamp
	}
	return nil
}

type GetNetworkParametersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNetworkParametersRequest) Reset()         { *m = GetNetworkParametersRequest{} }
func (m *GetNetworkParametersRequest) String() string { return proto.CompactTextString(m) }
func (*GetNetworkParametersRequest) ProtoMessage()    {}
func (*GetNetworkParametersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{30}
}

func (m *GetNetworkParametersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkParametersRequest.Unmarshal(m, b)
}
func (m *GetNetworkParametersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkParametersRequest.Marshal(b, m, deterministic)
}
func (m *GetNetworkParametersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkParametersRequest.Merge(m, src)
}
func (m *GetNetworkParametersRequest) XXX_Size() int {
	return xxx_messageInfo_GetNetworkParametersRequest.Size(m)
}
func (m *GetNetworkParametersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkParametersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkParametersRequest proto.InternalMessageInfo

type GetNetworkParametersResponse struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNetworkParametersResponse) Reset()         { *m = GetNetworkParametersResponse{} }
func (m *GetNetworkParametersResponse) String() string { return proto.CompactTextString(m) }
func (*GetNetworkParametersResponse) ProtoMessage()    {}
func (*GetNetworkParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{31}
}

func (m *GetNetworkParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkParametersResponse.Unmarshal(m, b)
}
func (m *GetNetworkParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkParametersResponse.Marshal(b, m, deterministic)
}
func (m *GetNetworkParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkParametersResponse.Merge(m, src)
}
func (m *GetNetworkParametersResponse) XXX_Size() int {
	return xxx_messageInfo_GetNetworkParametersResponse.Size(m)
}
func (m *GetNetworkParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkParametersResponse proto.InternalMessageInfo

func (m *GetNetworkParametersResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type GetLatestProtocolStateSnapshotRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestProtocolStateSnapshotRequest) Reset()         { *m = GetLatestProtocolStateSnapshotRequest{} }
func (m *GetLatestProtocolStateSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestProtocolStateSnapshotRequest) ProtoMessage()    {}
func (*GetLatestProtocolStateSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{32}
}

func (m *GetLatestProtocolStateSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestProtocolStateSnapshotRequest.Unmarshal(m, b)
}
func (m *GetLatestProtocolStateSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestProtocolStateSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *GetLatestProtocolStateSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestProtocolStateSnapshotRequest.Merge(m, src)
}
func (m *GetLatestProtocolStateSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestProtocolStateSnapshotRequest.Size(m)
}
func (m *GetLatestProtocolStateSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestProtocolStateSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestProtocolStateSnapshotRequest proto.InternalMessageInfo

type ProtocolStateSnapshotResponse struct {
	SerializedSnapshot   []byte   `protobuf:"bytes,1,opt,name=serializedSnapshot,proto3" json:"serializedSnapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtocolStateSnapshotResponse) Reset()         { *m = ProtocolStateSnapshotResponse{} }
func (m *ProtocolStateSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*ProtocolStateSnapshotResponse) ProtoMessage()    {}
func (*ProtocolStateSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{33}
}

func (m *ProtocolStateSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolStateSnapshotResponse.Unmarshal(m, b)
}
func (m *ProtocolStateSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolStateSnapshotResponse.Marshal(b, m, deterministic)
}
func (m *ProtocolStateSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolStateSnapshotResponse.Merge(m, src)
}
func (m *ProtocolStateSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_ProtocolStateSnapshotResponse.Size(m)
}
func (m *ProtocolStateSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolStateSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolStateSnapshotResponse proto.InternalMessageInfo

func (m *ProtocolStateSnapshotResponse) GetSerializedSnapshot() []byte {
	if m != nil {
		return m.SerializedSnapshot
	}
	return nil
}

type GetExecutionResultForBlockIDRequest struct {
	BlockId              []byte   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExecutionResultForBlockIDRequest) Reset()         { *m = GetExecutionResultForBlockIDRequest{} }
func (m *GetExecutionResultForBlockIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetExecutionResultForBlockIDRequest) ProtoMessage()    {}
func (*GetExecutionResultForBlockIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{34}
}

func (m *GetExecutionResultForBlockIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExecutionResultForBlockIDRequest.Unmarshal(m, b)
}
func (m *GetExecutionResultForBlockIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExecutionResultForBlockIDRequest.Marshal(b, m, deterministic)
}
func (m *GetExecutionResultForBlockIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExecutionResultForBlockIDRequest.Merge(m, src)
}
func (m *GetExecutionResultForBlockIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetExecutionResultForBlockIDRequest.Size(m)
}
func (m *GetExecutionResultForBlockIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExecutionResultForBlockIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetExecutionResultForBlockIDRequest proto.InternalMessageInfo

func (m *GetExecutionResultForBlockIDRequest) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

type ExecutionResultForBlockIDResponse struct {
	ExecutionResult      *entities.ExecutionResult `protobuf:"bytes,1,opt,name=execution_result,json=executionResult,proto3" json:"execution_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ExecutionResultForBlockIDResponse) Reset()         { *m = ExecutionResultForBlockIDResponse{} }
func (m *ExecutionResultForBlockIDResponse) String() string { return proto.CompactTextString(m) }
func (*ExecutionResultForBlockIDResponse) ProtoMessage()    {}
func (*ExecutionResultForBlockIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4382e32bb8e3e8e5, []int{35}
}

func (m *ExecutionResultForBlockIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionResultForBlockIDResponse.Unmarshal(m, b)
}
func (m *ExecutionResultForBlockIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionResultForBlockIDResponse.Marshal(b, m, deterministic)
}
func (m *ExecutionResultForBlockIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionResultForBlockIDResponse.Merge(m, src)
}
func (m *ExecutionResultForBlockIDResponse) XXX_Size() int {
	return xxx_messageInfo_ExecutionResultForBlockIDResponse.Size(m)
}
func (m *ExecutionResultForBlockIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionResultForBlockIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionResultForBlockIDResponse proto.InternalMessageInfo

func (m *ExecutionResultForBlockIDResponse) GetExecutionResult() *entities.ExecutionResult {
	if m != nil {
		return m.ExecutionResult
	}
	return nil
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "flow.access.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "flow.access.PingResponse")
	proto.RegisterType((*GetLatestBlockHeaderRequest)(nil), "flow.access.GetLatestBlockHeaderRequest")
	proto.RegisterType((*GetBlockHeaderByIDRequest)(nil), "flow.access.GetBlockHeaderByIDRequest")
	proto.RegisterType((*GetBlockHeaderByHeightRequest)(nil), "flow.access.GetBlockHeaderByHeightRequest")
	proto.RegisterType((*BlockHeaderResponse)(nil), "flow.access.BlockHeaderResponse")
	proto.RegisterType((*EntireBlockHeaderResponse)(nil), "flow.access.EntireBlockHeaderResponse")
	proto.RegisterType((*GetLatestBlockRequest)(nil), "flow.access.GetLatestBlockRequest")
	proto.RegisterType((*GetBlockByIDRequest)(nil), "flow.access.GetBlockByIDRequest")
	proto.RegisterType((*GetBlockByHeightRequest)(nil), "flow.access.GetBlockByHeightRequest")
	proto.RegisterType((*BlockResponse)(nil), "flow.access.BlockResponse")
	proto.RegisterType((*GetCollectionByIDRequest)(nil), "flow.access.GetCollectionByIDRequest")
	proto.RegisterType((*CollectionResponse)(nil), "flow.access.CollectionResponse")
	proto.RegisterType((*SendTransactionRequest)(nil), "flow.access.SendTransactionRequest")
	proto.RegisterType((*SendTransactionResponse)(nil), "flow.access.SendTransactionResponse")
	proto.RegisterType((*GetTransactionRequest)(nil), "flow.access.GetTransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "flow.access.TransactionResponse")
	proto.RegisterType((*TransactionResultResponse)(nil), "flow.access.TransactionResultResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "flow.access.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "flow.access.GetAccountResponse")
	proto.RegisterType((*GetAccountAtLatestBlockRequest)(nil), "flow.access.GetAccountAtLatestBlockRequest")
	proto.RegisterType((*AccountResponse)(nil), "flow.access.AccountResponse")
	proto.RegisterType((*GetAccountAtBlockHeightRequest)(nil), "flow.access.GetAccountAtBlockHeightRequest")
	proto.RegisterType((*ExecuteScriptAtLatestBlockRequest)(nil), "flow.access.ExecuteScriptAtLatestBlockRequest")
	proto.RegisterType((*ExecuteScriptAtBlockIDRequest)(nil), "flow.access.ExecuteScriptAtBlockIDRequest")
	proto.RegisterType((*ExecuteScriptAtBlockHeightRequest)(nil), "flow.access.ExecuteScriptAtBlockHeightRequest")
	proto.RegisterType((*ExecuteScriptResponse)(nil), "flow.access.ExecuteScriptResponse")
	proto.RegisterType((*GetEventsForHeightRangeRequest)(nil), "flow.access.GetEventsForHeightRangeRequest")
	proto.RegisterType((*GetEventsForBlockIDsRequest)(nil), "flow.access.GetEventsForBlockIDsRequest")
	proto.RegisterType((*EventsResponse)(nil), "flow.access.EventsResponse")
	proto.RegisterType((*EventsResponse_Result)(nil), "flow.access.EventsResponse.Result")
	proto.RegisterType((*GetNetworkParametersRequest)(nil), "flow.access.GetNetworkParametersRequest")
	proto.RegisterType((*GetNetworkParametersResponse)(nil), "flow.access.GetNetworkParametersResponse")
	proto.RegisterType((*GetLatestProtocolStateSnapshotRequest)(nil), "flow.access.GetLatestProtocolStateSnapshotRequest")
	proto.RegisterType((*ProtocolStateSnapshotResponse)(nil), "flow.access.ProtocolStateSnapshotResponse")
	proto.RegisterType((*GetExecutionResultForBlockIDRequest)(nil), "flow.access.GetExecutionResultForBlockIDRequest")
	proto.RegisterType((*ExecutionResultForBlockIDResponse)(nil), "flow.access.ExecutionResultForBlockIDResponse")
}

func init() { proto.RegisterFile("flow/access/access.proto", fileDescriptor_4382e32bb8e3e8e5) }

var fileDescriptor_4382e32bb8e3e8e5 = []byte{
	// 1416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x5b, 0x73, 0xd3, 0x46,
	0x14, 0x1e, 0x3b, 0x21, 0x89, 0x4f, 0x6e, 0xb0, 0x40, 0xb0, 0x15, 0x92, 0x98, 0xe5, 0xd2, 0x00,
	0x45, 0xa1, 0xb4, 0xd3, 0x16, 0xe8, 0x43, 0x43, 0x0a, 0x21, 0x33, 0x5c, 0x32, 0x32, 0xc3, 0x4c,
	0x2f, 0x34, 0x23, 0x4b, 0x8b, 0xad, 0x62, 0x4b, 0xae, 0x76, 0x0d, 0xa5, 0xd3, 0x07, 0x9e, 0xfb,
	0x8f, 0xfa, 0x7f, 0xfa, 0xda, 0xff, 0xd0, 0xd1, 0x6a, 0x57, 0xde, 0x95, 0x56, 0xb2, 0x07, 0x5e,
	0x20, 0xbb, 0xfb, 0x9d, 0xef, 0x9c, 0x3d, 0xe7, 0xec, 0xd1, 0x97, 0x40, 0xf3, 0xf5, 0x20, 0x7a,
	0xb7, 0xe7, 0x7a, 0x1e, 0xa1, 0x54, 0xfc, 0x67, 0x8f, 0xe2, 0x88, 0x45, 0x68, 0x39, 0x39, 0xb1,
	0xd3, 0x2d, 0x6b, 0x93, 0xc3, 0x48, 0xc8, 0x02, 0x16, 0x10, 0x0e, 0x8c, 0xc6, 0x21, 0x4b, 0x91,
	0x56, 0x5b, 0x3f, 0xec, 0x0e, 0x22, 0xef, 0xcd, 0x49, 0x9f, 0xb8, 0x3e, 0x89, 0x05, 0xa2, 0x65,
	0x40, 0x88, 0xa3, 0x6d, 0xfd, 0xc8, 0x8b, 0x06, 0x03, 0xe2, 0xb1, 0x20, 0x0a, 0xcd, 0xa6, 0xe4,
	0x2d, 0xc9, 0xfc, 0x5e, 0xc9, 0x1d, 0xfd, 0x41, 0xbc, 0x71, 0x62, 0x79, 0x12, 0x13, 0x3a, 0x1e,
	0x48, 0xd4, 0x8e, 0x8e, 0x62, 0xb1, 0x1b, 0x52, 0x57, 0xf5, 0xb0, 0xd3, 0x8b, 0xa2, 0xde, 0x80,
	0xec, 0xf1, 0x55, 0x77, 0xfc, 0x7a, 0x8f, 0x05, 0x43, 0x42, 0x99, 0x3b, 0x1c, 0xa5, 0x00, 0xbc,
	0x0a, 0xcb, 0xc7, 0x41, 0xd8, 0x73, 0xc8, 0xef, 0x63, 0x42, 0x19, 0x5e, 0x83, 0x95, 0x74, 0x49,
	0x47, 0x51, 0x48, 0x09, 0xbe, 0x07, 0x9b, 0x87, 0x84, 0x3d, 0x71, 0x19, 0xa1, 0xec, 0x41, 0x72,
	0xb3, 0xc7, 0xfc, 0xea, 0x02, 0x8e, 0x36, 0xa1, 0x11, 0xd0, 0x13, 0x4a, 0xdc, 0x01, 0xf1, 0x9b,
	0xb5, 0x76, 0x6d, 0x77, 0xc9, 0x59, 0x0a, 0x68, 0x87, 0xaf, 0xf1, 0x4d, 0x68, 0x1d, 0x12, 0xd5,
	0xea, 0xc1, 0xfb, 0xa3, 0x1f, 0xa4, 0xe5, 0x1a, 0xd4, 0x83, 0xd4, 0x64, 0xc5, 0xa9, 0x07, 0x3e,
	0xfe, 0x06, 0xb6, 0xf2, 0xe0, 0xc7, 0x24, 0xe8, 0xf5, 0x99, 0x34, 0xd8, 0x80, 0x85, 0x3e, 0xdf,
	0xe0, 0x46, 0xf3, 0x8e, 0x58, 0xe1, 0x43, 0x38, 0xab, 0x05, 0x96, 0x06, 0x8e, 0x6e, 0xc3, 0x29,
	0x5e, 0x09, 0x8e, 0x5e, 0xbe, 0x63, 0xd9, 0xbc, 0xe2, 0x32, 0x53, 0xb6, 0x6a, 0x92, 0x02, 0x71,
	0x07, 0x5a, 0x0f, 0x43, 0x16, 0xc4, 0xc4, 0x44, 0xf7, 0xb5, 0x4e, 0xd7, 0xce, 0xd1, 0x15, 0x0d,
	0x05, 0xe9, 0x57, 0x70, 0x5e, 0xcf, 0xdf, 0x4c, 0x99, 0xbb, 0x0a, 0x67, 0x65, 0x32, 0xaa, 0x72,
	0xf6, 0x05, 0x5c, 0x98, 0xc0, 0x66, 0xcb, 0xd6, 0x7d, 0x58, 0x15, 0x61, 0x88, 0x8b, 0xdd, 0xd0,
	0x2f, 0x76, 0xce, 0x94, 0x27, 0x79, 0x99, 0x1b, 0xd0, 0x3c, 0x24, 0xec, 0x20, 0xeb, 0xe2, 0xaa,
	0xd8, 0x9e, 0x03, 0x9a, 0x00, 0x33, 0x6f, 0x77, 0x01, 0x26, 0x8f, 0x40, 0xb8, 0x6c, 0xe5, 0x5c,
	0x2a, 0x66, 0x0a, 0x18, 0xbf, 0x84, 0x8d, 0x0e, 0x09, 0xfd, 0x17, 0x93, 0x16, 0x97, 0xae, 0xbf,
	0x83, 0x65, 0xa5, 0xf1, 0x4b, 0x0a, 0xae, 0xda, 0xa9, 0x70, 0x7c, 0x1d, 0x2e, 0x14, 0x78, 0x45,
	0xb4, 0xf9, 0x3b, 0x7d, 0xc6, 0x8b, 0x69, 0x88, 0x20, 0x0f, 0xec, 0xc0, 0x59, 0x13, 0xdf, 0xa7,
	0x05, 0xfa, 0x6f, 0x0d, 0x5a, 0x3a, 0xeb, 0x78, 0xc0, 0x32, 0xee, 0x6f, 0x61, 0x81, 0x32, 0x97,
	0x8d, 0x29, 0xa7, 0x5d, 0x2b, 0x74, 0xa8, 0x62, 0xd9, 0xe1, 0x38, 0x47, 0xe0, 0xd1, 0x0e, 0x2c,
	0xa7, 0x3f, 0x9d, 0x78, 0x91, 0x4f, 0x9a, 0xf5, 0x76, 0x6d, 0x77, 0xd5, 0x81, 0x74, 0xeb, 0x20,
	0xf2, 0x09, 0xba, 0x0c, 0xab, 0x24, 0x8e, 0xa3, 0xf8, 0x64, 0x48, 0x28, 0x75, 0x7b, 0xa4, 0x39,
	0xd7, 0xae, 0xed, 0x36, 0x9c, 0x15, 0xbe, 0xf9, 0x34, 0xdd, 0x43, 0x9f, 0xc3, 0x02, 0x1f, 0x5f,
	0xb4, 0x39, 0xdf, 0x9e, 0x33, 0x34, 0xd2, 0xc3, 0xe4, 0xd0, 0x11, 0x18, 0xd4, 0x82, 0xa5, 0x74,
	0x92, 0x06, 0x7e, 0xf3, 0x14, 0x4f, 0xdb, 0x22, 0x5f, 0x1f, 0xf9, 0xf8, 0x16, 0x9c, 0x39, 0x24,
	0x6c, 0x3f, 0x1d, 0xc2, 0x32, 0xc1, 0x4d, 0x58, 0x74, 0x7d, 0x3f, 0x26, 0x94, 0x8a, 0x2c, 0xcb,
	0x25, 0x7e, 0x04, 0x48, 0x85, 0x67, 0xaf, 0x7f, 0x51, 0x8c, 0x71, 0x91, 0xe5, 0x8d, 0x5c, 0x38,
	0xd2, 0x40, 0xc2, 0xf0, 0x3d, 0xd8, 0x9e, 0xf0, 0xec, 0x9b, 0x5e, 0x6c, 0x79, 0x0c, 0x07, 0xb0,
	0xfe, 0xe9, 0x01, 0xbc, 0xd2, 0x03, 0x10, 0xb3, 0x44, 0x7d, 0xd3, 0xa5, 0x01, 0xa0, 0x4b, 0xb0,
	0x22, 0x3f, 0x4c, 0xfc, 0xcd, 0xd7, 0xf9, 0x9b, 0x5f, 0xee, 0x4e, 0x38, 0xf0, 0x8f, 0x70, 0xe9,
	0x21, 0xff, 0x86, 0x90, 0x8e, 0x17, 0x07, 0x23, 0xf3, 0x15, 0x37, 0x60, 0x81, 0xf2, 0x53, 0xe1,
	0x40, 0xac, 0xd0, 0x45, 0x68, 0xb8, 0x71, 0x6f, 0x3c, 0xe4, 0xf5, 0xad, 0xb7, 0xe7, 0x76, 0x57,
	0x9c, 0xc9, 0x06, 0x1e, 0xc1, 0x56, 0x8e, 0x9a, 0x93, 0x4e, 0x66, 0x83, 0x5a, 0xed, 0x9a, 0x56,
	0x6d, 0xc5, 0x63, 0xbd, 0xdc, 0xe3, 0x5c, 0xde, 0xe3, 0x5f, 0x85, 0xcb, 0x18, 0xd2, 0x95, 0x4f,
	0x4a, 0xad, 0x90, 0x94, 0x8f, 0xf4, 0x7e, 0x0b, 0xce, 0x6b, 0xde, 0xb3, 0xa2, 0x9f, 0x83, 0x53,
	0x6f, 0xdd, 0xc1, 0x98, 0x88, 0x4b, 0xa6, 0x0b, 0xfc, 0x96, 0x17, 0x96, 0xf7, 0x3f, 0x7d, 0x14,
	0xc5, 0x22, 0x48, 0x37, 0xec, 0x11, 0x19, 0x29, 0x82, 0x79, 0xf6, 0x7e, 0x94, 0x9a, 0x35, 0x1c,
	0xfe, 0x73, 0x12, 0x3d, 0x65, 0x6e, 0xcc, 0x72, 0x25, 0xe5, 0x7b, 0x22, 0xfa, 0x2d, 0x00, 0x12,
	0xfa, 0x12, 0x30, 0xc7, 0x01, 0x0d, 0x12, 0xfa, 0xa2, 0xe2, 0xcf, 0xf8, 0xa7, 0x3b, 0xf3, 0x2b,
	0x6a, 0x42, 0xab, 0x9c, 0x6e, 0x42, 0x43, 0x16, 0x4a, 0xd6, 0x79, 0x49, 0x54, 0x8a, 0xe2, 0xbf,
	0xeb, 0xb0, 0x96, 0xb2, 0x29, 0x03, 0x6d, 0x31, 0x95, 0x23, 0x49, 0x47, 0x26, 0xaf, 0x1e, 0xdb,
	0x8a, 0xb0, 0xb2, 0x75, 0xb4, 0x2d, 0x26, 0x96, 0x34, 0xb1, 0xfe, 0xa9, 0xc1, 0x42, 0xba, 0x57,
	0xd5, 0x21, 0xd3, 0x7b, 0x5b, 0x99, 0x3d, 0x73, 0x33, 0xcc, 0x9e, 0x03, 0x58, 0x4f, 0x09, 0x33,
	0x29, 0xd4, 0x9c, 0x17, 0x93, 0x38, 0x15, 0x4b, 0xb6, 0x14, 0x4b, 0xf6, 0x0b, 0x89, 0x70, 0xd6,
	0xb8, 0x49, 0xb6, 0xc6, 0x5b, 0x3c, 0xb9, 0xcf, 0x08, 0x7b, 0x17, 0xc5, 0x6f, 0x8e, 0xdd, 0xd8,
	0x1d, 0x12, 0x46, 0x62, 0x99, 0x5c, 0x7c, 0x17, 0x2e, 0x9a, 0x8f, 0x45, 0xe2, 0x5a, 0xb0, 0xe4,
	0xf5, 0xdd, 0x20, 0x94, 0xf7, 0x6d, 0x38, 0x8b, 0x7c, 0x7d, 0x94, 0x7c, 0x64, 0xae, 0x66, 0x8a,
	0xe1, 0x38, 0x09, 0xc4, 0x8b, 0x06, 0xc9, 0xc4, 0x26, 0x9d, 0xd0, 0x1d, 0xd1, 0x7e, 0x24, 0xfb,
	0x1b, 0x3f, 0x87, 0xad, 0x92, 0x73, 0xe1, 0xc4, 0x06, 0x44, 0x49, 0x1c, 0xb8, 0x83, 0xe0, 0x4f,
	0xe2, 0xcb, 0x53, 0x91, 0x5e, 0xc3, 0x09, 0xfe, 0x1e, 0x2e, 0x27, 0x0d, 0x23, 0x95, 0x66, 0x5a,
	0x9a, 0x49, 0xe7, 0x4c, 0x7f, 0xcd, 0x38, 0x94, 0xef, 0xd2, 0x68, 0x2e, 0xc2, 0x3a, 0x82, 0xd3,
	0x79, 0x35, 0x2b, 0x66, 0xe4, 0x76, 0xbe, 0x6e, 0x3a, 0x97, 0xb3, 0x4e, 0xf4, 0x8d, 0x3b, 0xff,
	0x9d, 0x81, 0xc6, 0x3e, 0xef, 0xb5, 0xfd, 0xe3, 0x23, 0xf4, 0x1b, 0x97, 0x27, 0x05, 0x29, 0x96,
	0xa8, 0x14, 0x74, 0x4d, 0x6b, 0xcc, 0x52, 0x59, 0x6a, 0xe9, 0xb8, 0x72, 0x3d, 0x78, 0x1f, 0xe6,
	0x13, 0x9d, 0x8c, 0x9a, 0x1a, 0x5e, 0x51, 0xd2, 0x56, 0xcb, 0x70, 0x22, 0x8c, 0xbb, 0x70, 0xce,
	0x24, 0xaa, 0xd1, 0x6e, 0x3e, 0xc8, 0x32, 0xdd, 0x6d, 0xb5, 0x35, 0xa4, 0x29, 0xc0, 0x5f, 0xf9,
	0x77, 0xf1, 0x63, 0xd3, 0x30, 0x9d, 0xff, 0x35, 0x6c, 0x98, 0xf5, 0x3a, 0xba, 0x51, 0xe9, 0x43,
	0x9b, 0xd1, 0x33, 0xf8, 0x39, 0x86, 0x35, 0x3d, 0x11, 0x08, 0x57, 0x64, 0x49, 0xf2, 0x5a, 0x45,
	0xde, 0x8c, 0xf1, 0x09, 0xac, 0xa8, 0xe2, 0x1a, 0xb5, 0x8d, 0xf1, 0xaa, 0xd9, 0xa8, 0x62, 0x7b,
	0x01, 0xa7, 0xf3, 0x1a, 0x1c, 0x5d, 0x29, 0x61, 0xd4, 0xef, 0x5e, 0xc5, 0xfa, 0x33, 0x17, 0x41,
	0xba, 0xd2, 0x46, 0x57, 0xf3, 0xb4, 0x46, 0x25, 0x6e, 0xed, 0x68, 0x30, 0x83, 0x08, 0xff, 0x05,
	0xd6, 0x73, 0x8a, 0x17, 0x5d, 0xd6, 0x6c, 0xcc, 0x3a, 0xdb, 0xba, 0x52, 0x0d, 0x12, 0xec, 0x2f,
	0x79, 0xc1, 0x54, 0xf2, 0x42, 0xc1, 0x0c, 0xdc, 0x7a, 0x11, 0x4c, 0xbc, 0xe9, 0xa3, 0x29, 0x08,
	0xe0, 0x99, 0xd8, 0xaf, 0x55, 0xb0, 0xab, 0x22, 0xfa, 0x29, 0xc0, 0x44, 0x83, 0xa1, 0xed, 0x3c,
	0xb3, 0x2e, 0x4a, 0x73, 0x89, 0x36, 0xa8, 0x50, 0x9f, 0xff, 0x7e, 0x66, 0xd2, 0x94, 0xe8, 0x66,
	0x89, 0xad, 0x49, 0x96, 0x59, 0x17, 0x35, 0xf0, 0x14, 0x2f, 0x8a, 0x12, 0xaa, 0xf0, 0x52, 0xd4,
	0x4b, 0x53, 0xbc, 0x8c, 0xc0, 0x2a, 0xd7, 0x8f, 0xc8, 0xd6, 0xc7, 0xe6, 0x34, 0xa1, 0x69, 0xe1,
	0x72, 0x7c, 0xe6, 0xb1, 0x0f, 0x1b, 0x66, 0x59, 0x99, 0x9b, 0x30, 0x95, 0xda, 0x73, 0x26, 0x4f,
	0xc5, 0xbb, 0xa9, 0x49, 0xb4, 0xa7, 0x7a, 0xd3, 0xf3, 0x38, 0x8b, 0x47, 0x8f, 0xd7, 0xcc, 0xa4,
	0x09, 0x8b, 0x35, 0xab, 0x50, 0x8e, 0xd6, 0x66, 0x85, 0xde, 0x42, 0xaf, 0xf8, 0x8b, 0x29, 0x08,
	0xc0, 0xe2, 0x67, 0xa6, 0x4c, 0x23, 0x56, 0xd3, 0xbf, 0xe1, 0xf4, 0x05, 0x8d, 0x53, 0xa4, 0x2f,
	0x53, 0x49, 0xd6, 0xf5, 0x19, 0x90, 0xc2, 0xd9, 0x87, 0x1a, 0x57, 0xd1, 0x15, 0xb2, 0x08, 0xdd,
	0x31, 0x7f, 0x17, 0xaa, 0x34, 0x94, 0xa5, 0x77, 0x52, 0xb5, 0x9c, 0xfa, 0x50, 0xe3, 0xa2, 0xae,
	0x54, 0xe0, 0xa0, 0xdb, 0x85, 0xbc, 0x4e, 0x91, 0x52, 0x96, 0xa9, 0xb5, 0x2a, 0xa4, 0xd3, 0x83,
	0x27, 0x60, 0x45, 0x71, 0xcf, 0x8e, 0x42, 0x6e, 0x96, 0xc9, 0xd4, 0xd4, 0xfe, 0x27, 0xbb, 0x17,
	0xb0, 0xfe, 0xb8, 0x6b, 0x7b, 0xd1, 0x70, 0x2f, 0x85, 0xec, 0xf1, 0x7f, 0xb2, 0xbf, 0xfd, 0xf5,
	0xa2, 0x3d, 0xe5, 0x2f, 0xa2, 0xdd, 0x05, 0x7e, 0xf0, 0xe5, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0xe4, 0xe4, 0xdc, 0x27, 0x15, 0x00, 0x00,
}
